name: c-app
on:
  push:
    branches:
      - main

jobs:
  c-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -t baxdr/c-app:$GITHUB_SHA .
          docker push baxdr/c-app:$GITHUB_SHA
